config/routes.rb
Rails.application.routes.draw do
  resources :ventes
  resources :stocks
  resources :genres
  resources :couleurs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to: 'pages#home'

  resources :orders do
    resources :order_items
  end

  resources :produits do
    resources :categories
    resources :marques
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :produits, dependent: :destroy
  validates :name, presence: true
end

app/models/couleur.rb
class Couleur < ApplicationRecord
  has_many :produits, dependent: :destroy
  validates :name, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :produits, dependent: :destroy
  validates :name, presence: true
end

app/models/marque.rb
class Marque < ApplicationRecord
  has_many :produits, dependent: :destroy
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  enum status_order: STATUS_ORDER
  enum type_delivery: TYPE_DELIVERY
  enum status_delivery: STATUS_DELIVERY

  validates :type_delivery, presence: true

  monetize :total_cents
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :produit

  enum status_order_item: STATUS_ORDER_ITEM

  validates :quantite, presence: true
end

app/models/produit.rb
class Produit < ApplicationRecord
  belongs_to :marque
  belongs_to :category
  belongs_to :couleur
  belongs_to :genre
  has_many :stocks, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :ventes, dependent: :destroy
  has_many_attached :photos

  validates :name, presence: true
  validates :description, presence: true
  validates :reference, presence: true

  monetize :price_cents
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :produit

  validates :size, presence: true
  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :ventes, dependent: :destroy

  validates :nom, presence: true
  validates :prenom, presence: true
end

app/models/vente.rb
class Vente < ApplicationRecord
  belongs_to :produit
  belongs_to :user

  enum status_vente: STATUS_VENTE

  monetize :price_cents
end

app/controllers/ventes_controller.rb
class VentesController < ApplicationController
  before_action :set_vente, only: [:show, :edit, :update, :destroy]

  # GET /ventes
  # GET /ventes.json
  def index
    @ventes = Vente.all
  end

  # GET /ventes/1
  # GET /ventes/1.json
  def show
  end

  # GET /ventes/new
  def new
    @vente = Vente.new
  end

  # GET /ventes/1/edit
  def edit
  end

  # POST /ventes
  # POST /ventes.json
  def create
    @vente = Vente.new(vente_params)

    respond_to do |format|
      if @vente.save
        format.html { redirect_to @vente, notice: 'Vente was successfully created.' }
        format.json { render :show, status: :created, location: @vente }
      else
        format.html { render :new }
        format.json { render json: @vente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ventes/1
  # PATCH/PUT /ventes/1.json
  def update
    respond_to do |format|
      if @vente.update(vente_params)
        format.html { redirect_to @vente, notice: 'Vente was successfully updated.' }
        format.json { render :show, status: :ok, location: @vente }
      else
        format.html { render :edit }
        format.json { render json: @vente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventes/1
  # DELETE /ventes/1.json
  def destroy
    @vente.destroy
    respond_to do |format|
      format.html { redirect_to ventes_url, notice: 'Vente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vente
      @vente = Vente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vente_params
      params.require(:vente).permit(:produit_id, :user_id, :status_vente, :remboursement)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/couleurs_helper.rb
module CouleursHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/marques_helper.rb
module MarquesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/ventes_helper.rb
module VentesHelper
end

app/views/ventes/_form.html.erb
<%= simple_form_for(@vente) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :produit %>
    <%= f.input :prix %>
    <%= f.association :user %>
    <%= f.input :statut_vente %>
    <%= f.input :remboursement %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ventes/edit.html.erb
<h1>Editing Vente</h1>

<%= render 'form', vente: @vente %>

<%= link_to 'Show', @vente %> |
<%= link_to 'Back', ventes_path %>

app/views/ventes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ventes</h1>

<table>
  <thead>
    <tr>
      <th>Produit</th>
      <th>Prix</th>
      <th>User</th>
      <th>Statut vente</th>
      <th>Remboursement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ventes.each do |vente| %>
      <tr>
        <td><%= vente.produit_id %></td>
        <td><%= vente.prix %></td>
        <td><%= vente.user_id %></td>
        <td><%= vente.statut_vente %></td>
        <td><%= vente.remboursement %></td>
        <td><%= link_to 'Show', vente %></td>
        <td><%= link_to 'Edit', edit_vente_path(vente) %></td>
        <td><%= link_to 'Destroy', vente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vente', new_vente_path %>

app/views/ventes/new.html.erb
<h1>New Vente</h1>

<%= render 'form', vente: @vente %>

<%= link_to 'Back', ventes_path %>

app/views/ventes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Produit:</strong>
  <%= @vente.produit_id %>
</p>

<p>
  <strong>Prix:</strong>
  <%= @vente.prix %>
</p>

<p>
  <strong>User:</strong>
  <%= @vente.user_id %>
</p>

<p>
  <strong>Statut vente:</strong>
  <%= @vente.statut_vente %>
</p>

<p>
  <strong>Remboursement:</strong>
  <%= @vente.remboursement %>
</p>

<%= link_to 'Edit', edit_vente_path(@vente) %> |
<%= link_to 'Back', ventes_path %>