config/routes.rb
Rails.application.routes.draw do
  resources :ventes
  resources :stocks
  resources :genres
  resources :couleurs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to: 'pages#home'

  resources :orders do
    resources :order_items
  end

  resources :produits do
    resources :categories
    resources :marques
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :produits, dependent: :destroy
  validates :name, presence: true
end

app/models/couleur.rb
class Couleur < ApplicationRecord
  has_many :produits, dependent: :destroy
  validates :name, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :produits, dependent: :destroy
  validates :name, presence: true
end

app/models/marque.rb
class Marque < ApplicationRecord
  has_many :produits, dependent: :destroy
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  enum status_order: STATUS_ORDER
  enum type_delivery: TYPE_DELIVERY
  enum status_delivery: STATUS_DELIVERY

  validates :type_delivery, presence: true

  monetize :total_cents
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :produit

  enum status_order_item: STATUS_ORDER_ITEM

  validates :quantite, presence: true
end

app/models/produit.rb
class Produit < ApplicationRecord
  belongs_to :marque
  belongs_to :category
  belongs_to :couleur
  belongs_to :genre
  has_many :stocks, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :ventes, dependent: :destroy
  has_many_attached :photos

  validates :name, presence: true
  validates :description, presence: true
  validates :reference, presence: true

  monetize :price_cents
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :produit

  validates :size, presence: true
  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :ventes, dependent: :destroy

  validates :nom, presence: true
  validates :prenom, presence: true
end

app/models/vente.rb
class Vente < ApplicationRecord
  belongs_to :produit
  belongs_to :user

  enum status_vente: STATUS_VENTE

  monetize :price_cents
end

app/controllers/marques_controller.rb
class MarquesController < ApplicationController
  before_action :set_marque, only: [:show, :edit, :update, :destroy]

  # GET /marques
  # GET /marques.json
  def index
    @marques = Marque.all
  end

  # GET /marques/1
  # GET /marques/1.json
  def show
  end

  # GET /marques/new
  def new
    @marque = Marque.new
  end

  # GET /marques/1/edit
  def edit
  end

  # POST /marques
  # POST /marques.json
  def create
    @marque = Marque.new(marque_params)

    respond_to do |format|
      if @marque.save
        format.html { redirect_to @marque, notice: 'Marque was successfully created.' }
        format.json { render :show, status: :created, location: @marque }
      else
        format.html { render :new }
        format.json { render json: @marque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marques/1
  # PATCH/PUT /marques/1.json
  def update
    respond_to do |format|
      if @marque.update(marque_params)
        format.html { redirect_to @marque, notice: 'Marque was successfully updated.' }
        format.json { render :show, status: :ok, location: @marque }
      else
        format.html { render :edit }
        format.json { render json: @marque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marques/1
  # DELETE /marques/1.json
  def destroy
    @marque.destroy
    respond_to do |format|
      format.html { redirect_to marques_url, notice: 'Marque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marque
      @marque = Marque.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marque_params
      params.require(:marque).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/couleurs_helper.rb
module CouleursHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/marques_helper.rb
module MarquesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/ventes_helper.rb
module VentesHelper
end

app/views/marques/_form.html.erb
<%= form_with(model: marque, local: true) do |form| %>
  <% if marque.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marque.errors.count, "error") %> prohibited this marque from being saved:</h2>

      <ul>
        <% marque.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/marques/edit.html.erb
<h1>Editing Marque</h1>

<%= render 'form', marque: @marque %>

<%= link_to 'Show', @marque %> |
<%= link_to 'Back', marques_path %>

app/views/marques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marques</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marques.each do |marque| %>
      <tr>
        <td><%= marque.nom %></td>
        <td><%= link_to 'Show', marque %></td>
        <td><%= link_to 'Edit', edit_marque_path(marque) %></td>
        <td><%= link_to 'Destroy', marque, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marque', new_marque_path %>

app/views/marques/new.html.erb
<h1>New Marque</h1>

<%= render 'form', marque: @marque %>

<%= link_to 'Back', marques_path %>

app/views/marques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @marque.nom %>
</p>

<%= link_to 'Edit', edit_marque_path(@marque) %> |
<%= link_to 'Back', marques_path %>